all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.4.172, mac: '48:21:0b:3e:5c:b4', disk: sda, network_interface: eno1}

